- name: Install redis repo
  ansible.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: true
- name: enable redis module
  ansible.builtin.command: dnf module enable redis:remi-6.2 -y
- name: Install redis package
  ansible.builtin.package:
    name: redis
    state: present
- name: replace conf file
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: Enable and start redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: true