- name: appsetup
  ansible.builtin.include_role:
    name: common
    tasks_from: app-setup
- name: python installation
  ansible.builtin.include_role:
    name: common
    tasks_from: python
- name: system daemon
  ansible.builtin.include_role:
    name: common
    tasks_from: systemdaemon
