- name: appsetup
  ansible.builtin.include_role:
    name: common
    tasks_from: app-setup
- name: go installation
  ansible.builtin.include_role:
    name: common
    tasks_from: go
- name: system daemon
  ansible.builtin.include_role:
    name: common
    tasks_from: systemdaemon
