- name: Install mysql
  ansible.builtin.package:
    name: mysql
    state: present
- name: get data
  ansible.builtin.shell:  mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema
- name: schema
  ansible.builtin.debug:
    msg: "schema output is {{schema}}"
- name: Load Schema
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}}  < /app/schema/shipping.sql"
  when: schema.stdout != "1"