- name: Install python
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  loop:
  - python36
  - gcc
  - python3-devel
- name: Change the working directory to /app and run the command 
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app