- name: appsetup
  ansible.builtin.include_role:
    name: common
    tasks_from: app-setup
- name: nodejs installation
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs
- name: system daemon
  ansible.builtin.include_role:
    name: common
    tasks_from: systemdaemon
